version: '3.8'

services:

  db:
    image: postgres
    networks:
      - database
    restart: on-failure
    ports:
      - 5434:5432
    volumes:
      - ./database/data/prod:/var/lib/postgresql/data
    container_name: db
    env_file:
     - ./backend/.env.docker

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - webapp
      - database
    ports:
      - 4000:4000
    env_file:
        - ./backend/.env.docker
    depends_on:
      - db
    restart: always
    container_name: server

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - webapp
    ports:
      - 80:3000
    stdin_open: true
    restart: always
    container_name: web
    depends_on:
      - server

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
